#!/usr/bin/env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific

# description: cloud-agent daemon
# processname: cloud-agent

# /etc/init.d/cloud-agent
set -u # fail on unset variables
VERSION="${cloudVersion}"
HASH="${buildNumber}"
_SCRIPT=$0

case "${1:-}" in
  --version)
        echo -e ${VERSION}
        exit 0
        ;;
  --hash)
        echo -e ${HASH}
        exit 0
        ;;
esac

export HOME_DIR=""
if [ "$#" = 3 ] && [ $2 = "--home" ] ; then
  export HOME_DIR=$3
  echo "Allow running multiple agents on this host; will use custom Home Dir: $HOME_DIR"
fi

export CONFIG_FILE="$HOME_DIR/etc/cloud-agent/conf/cloud-agent.ini"

get_agent_property() {
  property_name="$1"
  value=$(awk -F "=" "/^${property_name}/ {print \$2}" ${CONFIG_FILE})
  echo $value
}

valid_path() {
  value=${1:?}
  value=$(readlink -m ${value})
  if [ "$value" == "/" ]; then
    echo "path $1 not valid" 1>&2
    exit 1
  fi
  echo ${value}
}


export PATH=/usr/sbin:/sbin:/usr/lib/cloud-server/*:$PATH
export CLOUD_CONF_DIR=${HOME_DIR}/etc/cloud-server/conf:$PATH

# Because Cloud rpm unpacks modules here on all systems
export PYTHONPATH=/usr/lib/cloud-agent/lib:${PYTHONPATH:-}

export CLOUD_PID_DIR=`get_agent_property piddir`
export CLOUD_PID_DIR=`valid_path "${CLOUD_PID_DIR:?}"`
export CLOUD_PID_DIR="${CLOUD_PID_DIR:?}"
export CLOUD_AGENT_LOG_DIR=`get_agent_property logdir`
export CLOUD_AGENT_LOG_DIR=`valid_path "${CLOUD_AGENT_LOG_DIR:?}"`
export CLOUD_AGENT_LOG_DIR="${CLOUD_AGENT_LOG_DIR:?}"
KEYSDIR=`get_agent_property keysdir`
KEYSDIR=`valid_path "${KEYSDIR:?}"`
KEYSDIR="${KEYSDIR:?}"

CLOUD_AGENT=cloud-agent
PYTHON_WRAP=/usr/bin/cloud-python-wrap
PIDFILE=${CLOUD_PID_DIR}/${CLOUD_AGENT}.pid
OUTFILE=${CLOUD_AGENT_LOG_DIR}/cloud-agent.out
LOGFILE=${CLOUD_AGENT_LOG_DIR}/cloud-agent.log
AGENT_SCRIPT=/usr/lib/cloud-agent/lib/cloud_agent/main.py
AGENT_TMP_DIR=/var/lib/cloud-agent/tmp
AGENT_WORKING_DIR=/var/lib/cloud-agent
CLOUD_AGENT_PY_SCRIPT=/usr/lib/cloud-agent/lib/cloud_agent/CloudAgent.py
COMMON_DIR=/usr/lib/cloud-agent/lib/cloud_commons
COMMON_DIR_AGENT=/usr/lib/cloud-agent/lib/cloud_commons
OK=0
NOTOK=1

current_user=`id -u -n`
current_group=`id -g -n`

if [ "$EUID" -ne 0 ] ; then
  echo "" | sudo -S -l > /dev/null 2>&1
  if [ "$?" != "0" ] ; then
    echo "You can't perform this operation as non-sudoer user. Please, re-login or configure sudo access for this user."
    exit 0
  fi
fi

# set reliable cwd for this and child processes.
cd ${AGENT_WORKING_DIR}


print_error(){
  echo "ERROR: $1"
}

print_bold(){
  tput bold
  echo "$1"
  tput sgr0
}

print_error_bold(){
  tput bold
  print_error "$1"
  tput sgr0
}

change_files_permissions() {
  if [ ! -z "${KEYSDIR}" ]; then
    cloud-sudo.sh chown -R ${current_user} "${KEYSDIR}"
  fi

  cloud-sudo.sh mkdir -p "${CLOUD_PID_DIR:?}"
  cloud-sudo.sh chown -R ${current_user} "${CLOUD_PID_DIR:?}/"
  cloud-sudo.sh mkdir -p "${CLOUD_AGENT_LOG_DIR:?}"
  cloud-sudo.sh chown -R ${current_user}:${current_group} "${CLOUD_AGENT_LOG_DIR:?}/"
  cloud-sudo.sh chown -R ${current_user} "/var/lib/cloud-agent/data/"
  cloud-sudo.sh chown -R ${current_user} "/var/lib/cloud-agent/cache/"
  cloud-sudo.sh chown 	${current_user} "/usr/lib/cloud-agent/"
  cloud-sudo.sh chown  ${current_user} "/var/lib/cloud-agent/cred"
}


if [ -z "${PYTHON:-}" ] ; then
  export PYTHON=`readlink ${PYTHON_WRAP}`
fi

# Trying to read the passphrase from an environment
if [ ! -z ${CLOUD_PASSPHRASE:-} ]; then
  RESOLVED_CLOUD_PASSPHRASE=${CLOUD_PASSPHRASE}
fi

# Reading the environment file
if [ -a /var/lib/cloud-agent/cloud-env.sh ]; then
  /var/lib/cloud-agent/cloud-sudo.sh chown -R $current_user "/var/lib/cloud-agent/cloud-env.sh"
  . /var/lib/cloud-agent/cloud-env.sh
fi

if [ ! -z ${CLOUD_AGENT_LOG_DIR} ]; then
  LOGFILE=${CLOUD_AGENT_LOG_DIR}/cloud-agent.log
fi

if [ ! -z ${CLOUD_AGENT_OUT_DIR:-} ]; then
  OUTFILE=$CLOUD_AGENT_OUT_DIR/cloud-agent.out
fi

if [ -z ${RESOLVED_CLOUD_PASSPHRASE:-} ] &&  [ ! -z ${CLOUD_PASSPHRASE:-} ]; then
  RESOLVED_CLOUD_PASSPHRASE=${CLOUD_PASSPHRASE:-}
  # If the passphrase is not defined yet, use the value from the env file
elif [ -z ${RESOLVED_CLOUD_PASSPHRASE:-} ]; then
  # Passphrase is not defined anywhere, set the default value
  RESOLVED_CLOUD_PASSPHRASE="DEV"
fi

export CLOUD_PASSPHRASE=${RESOLVED_CLOUD_PASSPHRASE}


get_python_version(){
 python - <<EOF
import sys
ver = tuple(sys.version_info)
print("{}{}".format(ver[0], ver[1]))
EOF
}

check_python_version ()
{
  echo "Verifying Python version compatibility..."
  local min_py_ver=27
  local curr_py_ver=$(get_python_version)

  if [ ${curr_py_ver} -lt ${min_py_ver} ]; then
    print_error "Found Python version ${curr_py_ver:0:1}.${curr_py_ver:1:1}. Cloud Agent requires Python version > ${min_py_ver:0:1}.${min_py_ver:1:1}"
    return ${NOTOK}
  fi
  echo "Using python " ${PYTHON}
  return ${OK}
}

check_cloud_common_dir ()
{
  echo "Checking cloud-common dir..."
  # recursively compare all files except 'pyc' and 'pyo' in agent common dir and actual common dir to ensure they are up to date
  diff -r ${COMMON_DIR} ${COMMON_DIR_AGENT} -x '*.py?'
  OUT=$?
  if [ ${OUT} -ne 0 ];then
    print_error "cloud_commons folder mismatch. ${COMMON_DIR} content should be the same as ${COMMON_DIR_AGENT}. Either cloud-agent is co-hosted with cloud-server and agent was upgraded without server or the link was broken."
    return ${NOTOK}
  fi
  return ${OK}
}

retcode=0

case "${1:-}" in
  start)
        check_python_version
        if [ "$?" -eq "${NOTOK}" ]; then
          exit -1
        fi
        echo "Checking for previously running Cloud Agent..."
        if [ -f ${PIDFILE} ]; then
          PID=`cloud-sudo.sh cat ${PIDFILE}`
          if ! (ps -p ${PID} >/dev/null 2>/dev/null); then
            echo "$PIDFILE found with no process. Removing $PID..."
            cloud-sudo.sh rm -f ${PIDFILE}
          else
            print_error_bold "$CLOUD_AGENT already running"
            echo "Check $PIDFILE for PID."
            exit -1
          fi
        fi
        change_files_permissions

        check_cloud_common_dir
        if [ "$?" -eq "$NOTOK" ]; then
          exit -1
        fi

        echo "Starting cloud-agent"

        if [ "${CLOUD_AGENT_RUN_IN_FOREGROUND:-}" == true ] ; then
          ${PYTHON} ${CLOUD_AGENT_PY_SCRIPT} "$@" > ${OUTFILE} 2>&1
          exit $?
        fi

        nohup ${PYTHON} ${CLOUD_AGENT_PY_SCRIPT} "$@" > ${OUTFILE} 2>&1 &

        sleep 2
        PID=$!
        echo "Verifying $CLOUD_AGENT process status..."
        if ! (ps -p ${PID} >/dev/null 2>/dev/null); then
          if [ -s ${OUTFILE} ]; then
            print_error "${CLOUD_AGENT} start failed. For more details, see ${OUTFILE}:"
            echo "===================="
            tail -n 10 ${OUTFILE}
            echo "===================="
          else
            print_error "${CLOUD_AGENT} start failed"
          fi
          echo "Agent out at: ${OUTFILE}"
          echo "Agent log at: ${LOGFILE}"
          exit -1
        fi

        # print warnings from agent using perl-regex. \K is required to cut off "warning tag"
        cat ${OUTFILE}|GREP_COLOR='01;33' grep --color=always -Po 'WARNING: \K(.*)'

        print_bold "Cloud Agent successfully started"
        echo "Agent PID at: ${PIDFILE}"
        echo "Agent out at: ${OUTFILE}"
        echo "Agent log at: ${LOGFILE}"
        ;;
  status)
        if [ -f ${PIDFILE} ]; then
          PID=`cloud-sudo.sh cat ${PIDFILE}`
          echo "Found ${CLOUD_AGENT} PID: ${PID}"
          if ! (ps -p $PID >/dev/null 2>/dev/null); then
            echo "${CLOUD_AGENT} not running. Stale PID File at: ${PIDFILE}"
            retcode=2
          else
            print_bold "$CLOUD_AGENT running."
            echo "Agent PID at: ${PIDFILE}"
            echo "Agent out at: ${OUTFILE}"
            echo "Agent log at: ${LOGFILE}"
          fi
        else
          print_bold "${CLOUD_AGENT} currently not running"
          retcode=3
        fi
        ;;
  stop)
        check_python_version
        if [ "$?" -eq "${NOTOK}" ]; then
          exit -1
        fi
        if [ -f ${PIDFILE} ]; then
          PID=`cloud-sudo.sh cat ${PIDFILE}`
          echo "Found ${CLOUD_AGENT} PID: ${PID}"
          if ! (ps -p ${PID} >/dev/null 2>/dev/null); then
            print_error_bold "${CLOUD_AGENT} not running. Stale PID File at: ${PIDFILE}"
          else
            echo "Stopping ${CLOUD_AGENT}"
            change_files_permissions
            ${PYTHON} ${AGENT_SCRIPT} stop

            status cloud-agent 2>/dev/null | grep start 1>/dev/null
            if [ "$?" -eq 0 ] ; then
              echo "Stopping ${CLOUD_AGENT} upstart job"
              stop cloud-agent > /dev/null
            fi
          fi
          echo "Removing PID file at ${PIDFILE}"
          cloud-sudo.sh rm -f ${PIDFILE}
          print_bold "${CLOUD_AGENT} successfully stopped"
        else
          print_bold "${CLOUD_AGENT} is not running. No PID found at ${PIDFILE}"
        fi
        ;;
  restart)
        echo -e "Restarting $CLOUD_AGENT"
        ${_SCRIPT} stop
        shift
        ${_SCRIPT} start "$@"
        retcode=$?
        ;;
  reset)
          if [ "$#" -ne 2 ]; then
            echo "You must supply the hostname of the Cloud Server with the restore option. (e.g. cloud-agent reset c6401.cloud.apache.org)"
            exit 1
          fi
          if [ -f ${PIDFILE} ]; then
            echo "${CLOUD_AGENT} is running. You must stop it before using reset."
            exit 1
          fi
          echo -e "Resetting ${CLOUD_AGENT}"
          change_files_permissions
          ${PYTHON} ${AGENT_SCRIPT} reset $2
          retcode=$?

          if [ ${retcode} -eq 0 ]; then
            print_bold "${CLOUD_AGENT} has been reset successfully. Changed Cloud Server hostname to $2 and certificates were cleared."
          else
            print_bold "${CLOUD_AGENT} could not be reset."
          fi
          ;;

  *)
        print_bold "Usage: ${_SCRIPT} {start|stop|restart|status|reset <server_hostname>}"
        retcode=1
esac

exit ${retcode}
