---
- name: Big Data Service Management
  hosts: all
  become: yes
  tasks:
    - name: Ensure HDFS is running
      systemd:
        name: hadoop-hdfs-namenode
        state: started
        enabled: yes

    - name: Push new configuration to nodes
      template:
        src: hdfs-site.xml.j2
        dest: /etc/hadoop/conf/hdfs-site.xml
      notify: Restart HDFS
