#!/usr/bin/env python3

"""
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import os
import re
import time
import logging
import threading
from configparser import NoOptionError
from typing import List, Dict, Tuple, Optional

logger = logging.getLogger(__name__)


class IntelligentDataCleaner(threading.Thread):
    """
    Intelligent Data Cleaning System
    ================================
    
    This system provides automated, policy-driven cleaning of temporary files 
    generated by agent operations. Key features:
    
    - Multi-strategy cleanup policies
    - Age-based cleanup (remove files older than X)
    - Size-based cleanup (clean until under size threshold)
    - Pattern-aware file selection
    - Graceful throttling for large directories
    - Detailed cleaning analytics
    """
    
    # File patterns for cleanup
    COMMAND_FILE_PATTERN = r"errors-\d+\.txt|output-\d+\.txt|site-\d+\.pp|structured-out-\d+\.json|command-\d+\.json"
    AUTO_FILE_PATTERN = r"auto_command-\d+\.json|auto_errors-\d+\.txt|auto_output-\d+\.txt|auto_structured-out-\d+\.json"
    FILE_PATTERN = f"{AUTO_FILE_PATTERN}|{COMMAND_FILE_PATTERN}"
    
    # Cleanup modes
    CLEAN_AGGRESSIVE = 1
    CLEAN_MODERATE = 2
    CLEAN_CONSERVATIVE = 3
    
    # Constants
    MIN_AGE_SECONDS = 86400  # 24 hours (minimum retention)
    MIN_CLEAN_INTERVAL = 3600  # 1 hour (minimum interval)
    MAX_DIR_SIZE_MB = 10000  # 10 GB (maximum data size)

    def __init__(self, config, cleanup_mode=CLEAN_MODERATE):
        """
        Initialize the data cleaner
        
        :param config: Agent configuration instance
        :param cleanup_mode: Cleaning strategy (1=Aggressive, 2=Moderate, 3=Conservative)
        """
        super().__init__(daemon=True)
        self.config = config
        self.cleanup_mode = cleanup_mode
        self.stopped = threading.Event()
        self.compiled_pattern = re.compile(self.FILE_PATTERN)
        
        # Load configurations
        self.data_dir = self._get_config("agent", "prefix", "/var/lib/cloud-agent")
        self.file_max_age = self._get_numeric_config(
            "agent", "data_cleanup_max_age", self.MIN_AGE_SECONDS
        )
        self.cleanup_interval = self._get_numeric_config(
            "agent", "data_cleanup_interval", self.MIN_CLEAN_INTERVAL
        )
        self.max_dir_size_mb = self._get_numeric_config(
            "agent", "data_cleanup_max_size_MB", self.MAX_DIR_SIZE_MB
        )
        
        # Adjust retention time based on cleanup mode
        if self.cleanup_mode == self.CLEAN_CONSERVATIVE:
            self.file_max_age *= 2  # Double retention time
        elif self.cleanup_mode == self.CLEAN_AGGRESSIVE:
            self.file_max_age = int(self.MIN_AGE_SECONDS / 2)  # Half retention time
        
        self.current_stats = {
            "total_files": 0,
            "total_size_mb": 0,
            "files_removed": 0,
            "disk_freed_mb": 0,
            "last_clean_time": None
        }
        
        logger.info(
            "Data cleaner initialized: mode=%s, dir=%s, max_age=%ds, interval=%ds, max_size=%dMB",
            cleanup_mode, self.data_dir, self.file_max_age, 
            self.cleanup_interval, self.max_dir_size_mb
        )

    def _get_config(self, section: str, option: str, default: str) -> str:
        """Safely get configuration option with default"""
        try:
            return self.config.get(section, option, fallback=default)
        except NoOptionError:
            return default

    def _get_numeric_config(self, section: str, option: str, default: int) -> int:
        """Get numeric configuration with validation"""
        try:
            value = self.config.get(section, option, fallback=str(default))
            num_value = int(value) if value else default
            
            # Apply limits based on option type
            if option == "data_cleanup_max_age":
                return max(num_value, self.MIN_AGE_SECONDS)
            elif option == "data_cleanup_interval":
                return max(num_value, self.MIN_CLEAN_INTERVAL)
            elif option == "data_cleanup_max_size_MB":
                return min(max(num_value, 100), self.MAX_DIR_SIZE_MB)  # Min 100MB, max 10GB
        except (ValueError, TypeError):
            logger.warning("Invalid numeric config for %s: %s. Using default %d", 
                          option, value, default)
        return default

    def run(self):
        """Main cleaning loop"""
        logger.info("Data cleaner started in mode %d", self.cleanup_mode)
        
        while not self.stopped.is_set():
            try:
                start_time = time.monotonic()
                logger.info("Starting data cleanup cycle")
                
                # Execute cleaning processes
                self.cleanup_by_age()
                self.cleanup_by_size()
                
                # Update stats
                duration = time.monotonic() - start_time
                self.current_stats["last_clean_time"] = time.time()
                self.current_stats["clean_duration"] = duration
                
                logger.info(
                    "Cleanup completed: Removed %d files, Freed %dMB, Duration %.1fs",
                    self.current_stats.get("files_removed", 0),
                    self.current_stats.get("disk_freed_mb", 0),
                    duration
                )
                
                # Reset stats for next run
                self.current_stats["files_removed"] = 0
                self.current_stats["disk_freed_mb"] = 0
            except Exception as e:
                logger.error("Exception during cleaning cycle: %s", str(e))
            
            # Wait for next cycle or stop signaled
            stopped_wait = self.stopped.wait(self.cleanup_interval)
            if stopped_wait:
                break
        
        logger.info("Data cleaner thread stopped")

    def cleanup_by_age(self):
        """Remove files older than max age"""
        current_time = time.time()
        files_total = 0
        files_scanned = 0
        removed_count = 0
        
        logger.debug("Starting age-based cleanup (max_age=%ds)", self.file_max_age)
        
        for dirpath, _, filenames in os.walk(self.data_dir):
            files_total += len(filenames)
            
            for filename in filenames:
                if self.stopped.is_set():
                    return
                    
                if not self.compiled_pattern.match(filename):
                    continue
                    
                files_scanned += 1
                file_path = os.path.join(dirpath, filename)
                
                try:
                    file_mtime = os.path.getmtime(file_path)
                    file_age = current_time - file_mtime
                    
                    if file_age > self.file_max_age:
                        file_size = os.path.getsize(file_path)
                        os.remove(file_path)
                        removed_count += 1
                        
                        # Update stats
                        self.current_stats["files_removed"] += 1
                        self.current_stats["disk_freed_mb"] += (file_size / (1024 * 1024))
                        
                        if logger.isEnabledFor(logging.DEBUG) and removed_count % 100 == 0:
                            logger.debug("Removed %d old files...", removed_count)
                except OSError as e:
                    logger.error("Error removing file %s: %s", file_path, str(e))
        
        logger.info(
            "Age-based cleanup: Scanned %d/%d files, Removed %d files",
            files_scanned, files_total, removed_count
        )

    def cleanup_by_size(self):
        """Clean files until total size is under limit"""
        logger.debug("Starting size-based cleanup (max_size=%dMB)", self.max_dir_size_mb)
        
        # Get all candidate files with metadata
        file_metadata = self._collect_file_metadata()
        total_size_bytes = sum(size for _, size in file_metadata.values())
        max_size_bytes = self.max_dir_size_mb * 1024 * 1024
        
        if total_size_bytes < max_size_bytes:
            logger.debug("Directory size %dMB < limit %dMB, skipping size cleanup", 
                         total_size_bytes / (1024 * 1024), self.max_dir_size_mb)
            return
            
        # Sort files by oldest first
        sorted_files = sorted(
            file_metadata.items(), 
            key=lambda x: x[1][0]  # Sort by modification time
        )
        
        logger.info(
            "Directory size %dMB exceeds limit %dMB, will clean oldest files",
            total_size_bytes / (1024 * 1024), self.max_dir_size_mb
        )
        
        # Remove oldest files until under size limit
        removed_count = 0
        for file_path, (mtime, size) in sorted_files:
            if self.stopped.is_set():
                return
                
            if total_size_bytes <= max_size_bytes:
                break
                
            try:
                os.remove(file_path)
                removed_count += 1
                total_size_bytes -= size
                
                # Update stats
                self.current_stats["files_removed"] += 1
                self.current_stats["disk_freed_mb"] += (size / (1024 * 1024))
            except OSError as e:
                logger.error("Error removing file %s: %s", file_path, str(e))
        
        logger.info(
            "Size-based cleanup: Removed %d files, New size: %.1fMB",
            removed_count, total_size_bytes / (1024 * 1024)
        )

    def _collect_file_metadata(self) -> Dict[str, Tuple[float, int]]:
        """Collect metadata for candidate files"""
        file_metadata = {}
        
        for dirpath, _, filenames in os.walk(self.data_dir):
            if self.stopped.is_set():
                return {}
                
            for filename in filenames:
                if not self.compiled_pattern.match(filename):
                    continue
                    
                file_path = os.path.join(dirpath, filename)
                
                try:
                    stat = os.stat(file_path)
                    file_metadata[file_path] = (stat.st_mtime, stat.st_size)
                except OSError:
                    continue  # Skip inaccessible files
        
        return file_metadata

    def get_metrics(self) -> Dict[str, any]:
        """Get data cleaner metrics"""
        return {
            "cleaner_mode": self.cleanup_mode,
            "max_age_seconds": self.file_max_age,
            "clean_interval": self.cleanup_interval,
            "max_dir_size_mb": self.max_dir_size_mb,
            "files_removed": self.current_stats.get("files_removed", 0),
            "disk_freed_mb": self.current_stats.get("disk_freed_mb", 0),
            "last_run": self.current_stats.get("last_clean_time", 0),
            "next_run": self.current_stats.get("last_clean_time", 0) + self.cleanup_interval \
                         if self.current_stats.get("last_clean_time") else 0
        }

    def stop(self) -> None:
        """Gracefully stop the cleaner thread"""
        logger.info("Stopping data cleaner thread")
        self.stopped.set()
    
    def __del__(self):
        """Destructor for resource cleanup"""
        if not self.stopped.is_set():
            self.stop()
        logger.info("Data cleaner deallocated")


def start_data_cleaner(config, mode: int = IntelligentDataCleaner.CLEAN_MODERATE) -> IntelligentDataCleaner:
    """
    Start a managed data cleaner instance
    
    :param config: Configuration object
    :param mode: Cleaning mode (1: aggressive, 2: moderate, 3: conservative)
    :return: Running cleaner instance
    """
    cleaner = IntelligentDataCleaner(config, mode)
    cleaner.start()
    return cleaner


def main():
    """Demonstration of cleaner functionality"""
    # Mock configuration
    class MockConfig:
        def get(self, section, option, fallback=None):
            return {
                ("agent", "prefix"): "/tmp/cloud-agent",
                ("agent", "data_cleanup_max_age"): "18000",  # 5 hours
                ("agent", "data_cleanup_interval"): "1800",  # 30 min
                ("agent", "data_cleanup_max_size_MB"): "500"  # 500MB
            }.get((section, option), fallback)

        def __del__(self):
            print("Mock config released")

    # Start cleaner in conservative mode
    config = MockConfig()
    cleaner = start_data_cleaner(config, IntelligentDataCleaner.CLEAN_CONSERVATIVE)
    
    try:
        print("Data cleaner running. Press Ctrl+C to stop.")
        while cleaner.is_alive():
            time.sleep(1)
            # Print metrics every 10 seconds
            if int(time.time()) % 10 == 0:
                metrics = cleaner.get_metrics()
                print(f"Cleaner Metrics: Files removed={metrics['files_removed']}, Freed={metrics['disk_freed_mb']:.1f}MB")
    except KeyboardInterrupt:
        print("\nStopping data cleaner...")
        cleaner.stop()
        cleaner.join(timeout=5.0)
        if cleaner.is_alive():
            print("Warning: Cleaner thread didn't stop in time")
        else:
            print("Cleaner stopped successfully")


if __name__ == "__main__":
    import logging
    logging.basicConfig(level=logging.INFO)
    main()
