server:
  port: 8080

spring:
  application:
    name: cloudrealm-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
    gateway:
      routes:
        - id: platform-service
          uri: lb://cloudrealm-platform
          predicates:
            - Path=/api/**
        - id: aiops-service
          uri: http://localhost:8081 # Python AIOps Engine
          predicates:
            - Path=/api/aiops/**
